version: '3'
services:
  minio:
    image: minio:latest
    build:
      context: .
    volumes:
      - data1:/data
    expose:
      - "9000"
    env_file:
      - minio.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - minio.env
    volumes:
      - ./code:/opt
    entrypoint:
      - /opt/createbuckets.sh

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:9000"
    depends_on:
      - minio

volumes:
  data1:
